### ISSUE TITLE
不能编译

### ISSUE THREAD

**Issue by xmxsuperstar** [shinexiao/emark#1]
pom里的 http://192.168.0.222:8081/nexus/content/repositories/releases/ 这个库是私有仓库，而以下两个依赖在中央仓库又没有：

``` xml
        <dependency>
            <groupId>com.github.rjeschke</groupId>
            <artifactId>txtmark</artifactId>
            <version>0.11</version>
        </dependency>
        <dependency>
            <groupId>com.steadystate</groupId>
            <artifactId>css</artifactId>
            <version>0.9.7</version>
        </dependency>
```

**Comment by shinexiao** [comment]
你好，里面的两个jar包是使用的第三方开源的jar包，你可以在

markdown解析
https://github.com/rjeschke/txtmark 

css解析
http://sourceforge.net/projects/cssparser/files/cssparser/  目前最新版本是0.9.10

下载然后放到自己的nexus私服里面。

shine@easymin.com

发件人： xmxsuperstar
发送时间： 2013-08-30 14:28
收件人： shinexiao/emark
主题： [emark] 不能编译 (#1)
pom里的http://192.168.0.222:8081/nexus/content/repositories/releases/这个库是私有仓库，而以下两个依赖在中央仓库又没有：
···xml

com.github.rjeschke
txtmark
0.11

com.steadystate
css
0.9.7

···
